# Generated by Django 4.2.18 on 2025-02-08 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_uri', models.URLField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scopes', models.TextField()),
                ('universe_domain', models.TextField(blank=True, null=True)),
                ('account', models.TextField(blank=True, null=True)),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
